import { describe, it, expect } from "bun:test";
import { classifyChanges, parseChangedFiles, AUTO_COMMIT_WHITELIST } from "../../../../.claude/scripts/git-sync.js";

// Plan B 防回歸：maintainer hook 只 auto-commit 白名單檔案，避免搶走 agent
// 還沒 commit 的 code 變更（race condition）。
//
// 對應問題：今天 dispatch-e2e executor agent 寫完 integration test 還沒
// commit，maintainer hook 搶先把 test 檔包進 chore(maintainer): 更新數據檔案
// 與報告內容，吃掉了 agent 要用的 test(dispatch): e2e 閉環測試 4 cases
// convention message。

describe("classifyChanges (path whitelist)", () => {
	it("純 data 檔全部進 data 桶", () => {
		const r = classifyChanges([
			"data/scores.json",
			"data/improvements.jsonl",
			"reports/poc-1.md",
			"metrics/pulse.metrics",
			"random.jsonl",
		]);
		expect(r.data.length).toBe(5);
		expect(r.code.length).toBe(0);
	});

	it("純 code 檔全部進 code 桶", () => {
		const r = classifyChanges([
			"tests/unit/foo.test.js",
			"scripts/maintainer.js",
			"hooks/modules/guards.js",
			"rules/核心/任務管理.md",
			"skills/nova-eval/SKILL.md",
			"src/main.ts",
		]);
		expect(r.data.length).toBe(0);
		expect(r.code.length).toBe(6);
	});

	it("混合：分類正確不互相污染", () => {
		const r = classifyChanges([
			"data/scores.json",
			"tests/foo.js",
			"reports/r1.md",
			"scripts/x.js",
		]);
		expect(r.data).toEqual(["data/scores.json", "reports/r1.md"]);
		expect(r.code).toEqual(["tests/foo.js", "scripts/x.js"]);
	});

	it("spec/index.md（auto-generated by spec-tasks.js）算 data", () => {
		const r = classifyChanges(["spec/index.md", "spec/待做/abc.md"]);
		expect(r.data).toEqual(["spec/index.md"]);
		expect(r.code).toEqual(["spec/待做/abc.md"]);
	});

	it(".claude/ralph-loop.local.md（auto-managed）算 data", () => {
		const r = classifyChanges([".claude/ralph-loop.local.md", ".claude/settings.json"]);
		expect(r.data).toEqual([".claude/ralph-loop.local.md"]);
		expect(r.code).toEqual([".claude/settings.json"]);
	});

	it("空陣列 → 兩桶都空", () => {
		expect(classifyChanges([])).toEqual({ data: [], code: [] });
	});

	it("非 jsonl 但檔名含 .json 屬於 code（除非在 data/）", () => {
		const r = classifyChanges(["package.json", "src/config.json"]);
		expect(r.data.length).toBe(0);
		expect(r.code.length).toBe(2);
	});

	it("WHITELIST 是 RegExp 陣列", () => {
		expect(Array.isArray(AUTO_COMMIT_WHITELIST)).toBe(true);
		for (const re of AUTO_COMMIT_WHITELIST) {
			expect(re).toBeInstanceOf(RegExp);
		}
	});
});

describe("parseChangedFiles", () => {
	it("解析普通 porcelain 行", () => {
		const raw = ` M data/scores.json\n?? reports/new.md\n M scripts/x.js`;
		expect(parseChangedFiles(raw)).toEqual([
			"data/scores.json",
			"reports/new.md",
			"scripts/x.js",
		]);
	});

	it("rename 行取 new path", () => {
		const raw = `R  old/path.md -> new/path.md`;
		expect(parseChangedFiles(raw)).toEqual(["new/path.md"]);
	});

	it("空字串 → 空陣列", () => {
		expect(parseChangedFiles("")).toEqual([]);
		expect(parseChangedFiles(null)).toEqual([]);
	});

	it("混合 modified / added / renamed", () => {
		const raw = ` M data/a.json\nA  data/b.json\nR  old.md -> data/new.md\n?? scripts/c.js`;
		expect(parseChangedFiles(raw)).toEqual([
			"data/a.json",
			"data/b.json",
			"data/new.md",
			"scripts/c.js",
		]);
	});
});

describe("整合場景：今天的 race 不會再發生", () => {
	it("agent 寫 tests/dispatch-e2e.test.js + maintainer 動 data/scores.json → 只 commit data，跳過 test", () => {
		const changed = parseChangedFiles(` M data/scores.json\n?? tests/dispatch-e2e.test.js`);
		const { data, code } = classifyChanges(changed);
		expect(data).toEqual(["data/scores.json"]);
		expect(code).toEqual(["tests/dispatch-e2e.test.js"]);
		// 實際 execCommit 行為：committable.length > 0 → 只 add data，code 留給 agent
	});

	it("純 code 變更 → committable=0 → execCommit 應 return 不 commit", () => {
		const changed = parseChangedFiles(` M tests/foo.js\nM  scripts/bar.js`);
		const { data, code } = classifyChanges(changed);
		expect(data.length).toBe(0);
		expect(code.length).toBe(2);
		// 實際 execCommit 行為：committable.length === 0 → log 並 return
	});
});
