// skill-janitor.test.js — Skill 庫存管理單元測試
import { describe, test, expect, beforeEach, afterEach } from 'bun:test';
import { writeFileSync, mkdirSync, rmSync, existsSync, appendFileSync, readdirSync, readFileSync } from 'fs';
import { join } from 'path';
import { tmpdir } from 'os';
import { checkSkillHealth } from '../../node_modules/../../../.claude/scripts/skill-janitor.js';

// ─── 模組 export 驗證 ─────────────────────────────────────────────────────────

describe('skill-janitor exports', () => {
  test('checkSkillHealth 是函式且可呼叫', () => {
    expect(typeof checkSkillHealth).toBe('function');
    // 在真實 ~/.claude/ 上執行（唯讀，不會改動）
    const result = checkSkillHealth();
    expect(result).toHaveProperty('total');
    expect(result).toHaveProperty('referenced');
    expect(result).toHaveProperty('unreferenced');
    expect(typeof result.total).toBe('number');
    expect(Array.isArray(result.referenced)).toBe(true);
    expect(Array.isArray(result.unreferenced)).toBe(true);
  });

  test('pruneUnusedSkills 是函式', async () => {
    const mod = await import('../../node_modules/../../../.claude/scripts/skill-janitor.js');
    expect(typeof mod.pruneUnusedSkills).toBe('function');
  });
});

// ─── 沙箱邏輯測試 ─────────────────────────────────────────────────────────────

let TMP_DIR;
let skillsDir;
let agentsDir;
let lifecycleFile;

function createSkill(name) {
  const dir = join(skillsDir, name);
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, 'SKILL.md'), `---\nname: ${name}\n---\n# ${name}\n`);
}

function createAgent(name, skills = []) {
  const skillsYaml = skills.length > 0
    ? `skills:\n${skills.map((s) => `  - ${s}`).join('\n')}\n`
    : '';
  writeFileSync(join(agentsDir, `${name}.md`), `---\nname: ${name}\n${skillsYaml}---\n`);
}

function appendLifecycleEntry(entry) {
  appendFileSync(lifecycleFile, JSON.stringify(entry) + '\n');
}

function listSkills() {
  return readdirSync(skillsDir).filter(
    (d) => !d.startsWith('.') && existsSync(join(skillsDir, d, 'SKILL.md'))
  );
}

function collectReferenced() {
  const referenced = new Set();
  if (!existsSync(agentsDir)) return referenced;
  for (const f of readdirSync(agentsDir).filter((f) => f.endsWith('.md'))) {
    try {
      const content = readFileSync(join(agentsDir, f), 'utf-8');
      const match = content.match(/skills:\n((?:\s+-\s+.+\n)*)/);
      if (match) {
        for (const line of match[1].split('\n')) {
          const m = line.match(/^\s+-\s+(.+)/);
          if (m) referenced.add(m[1].trim());
        }
      }
    } catch (e) {
      console.error(`collectReferenced error: ${e.message}`);
    }
  }
  return referenced;
}

function collectAutoGenerated() {
  const autoGenerated = new Set();
  if (!existsSync(lifecycleFile)) return autoGenerated;
  try {
    readFileSync(lifecycleFile, 'utf-8').trim().split('\n')
      .forEach((l) => {
        try { const e = JSON.parse(l); if (e.action === 'forge' && e.skillName) autoGenerated.add(e.skillName); } catch (e) {
          console.error(`collectAutoGenerated parse error: ${e.message}`);
        }
      });
  } catch (e) {
    console.error(`collectAutoGenerated read error: ${e.message}`);
  }
  return autoGenerated;
}

beforeEach(() => {
  TMP_DIR = join(tmpdir(), `skill-janitor-test-${Date.now()}`);
  skillsDir = join(TMP_DIR, 'skills');
  agentsDir = join(TMP_DIR, 'agents');
  mkdirSync(skillsDir, { recursive: true });
  mkdirSync(agentsDir, { recursive: true });
  lifecycleFile = join(TMP_DIR, 'data', 'lifecycle.jsonl');
  mkdirSync(join(TMP_DIR, 'data'), { recursive: true });
});

afterEach(() => {
  if (existsSync(TMP_DIR)) rmSync(TMP_DIR, { recursive: true });
});

// ─── collectReferenced 邏輯 ────────────────────────────────────────────────────

describe('collectReferenced 邏輯', () => {
  test('正確解析 agent skills YAML 區段', () => {
    createAgent('executor', ['code-review', 'testing']);
    createAgent('planner', ['nova-spec']);
    const referenced = collectReferenced();
    expect(referenced.has('code-review')).toBe(true);
    expect(referenced.has('testing')).toBe(true);
    expect(referenced.has('nova-spec')).toBe(true);
    expect(referenced.size).toBe(3);
  });

  test('無 skills 欄位的 agent 不產生引用', () => {
    writeFileSync(join(agentsDir, 'simple.md'), '---\nname: simple\n---\n');
    const referenced = collectReferenced();
    expect(referenced.size).toBe(0);
  });
});

// ─── pruneUnusedSkills 邏輯 ────────────────────────────────────────────────────

describe('pruneUnusedSkills 邏輯', () => {
  const MAX_SKILLS = 35;

  test('skill 數量 <= MAX_SKILLS 時不觸發歸檔', () => {
    for (let i = 1; i <= 35; i++) createSkill(`skill-${i}`);
    const allSkills = listSkills();
    expect(allSkills.length).toBe(35);
    expect(allSkills.length <= MAX_SKILLS).toBe(true);
  });

  test('只歸檔未被引用且 lifecycle 有記錄的自動生成 skill', () => {
    for (let i = 1; i <= 37; i++) createSkill(`skill-${i}`);
    appendLifecycleEntry({ action: 'forge', skillName: 'skill-36', date: '2026-03-17' });
    appendLifecycleEntry({ action: 'forge', skillName: 'skill-37', date: '2026-03-17' });
    createAgent('executor', ['skill-36']);

    const allSkills = listSkills();
    expect(allSkills.length > MAX_SKILLS).toBe(true);

    const referenced = collectReferenced();
    const autoGenerated = collectAutoGenerated();
    const toPrune = allSkills.filter((s) => !referenced.has(s) && autoGenerated.has(s));

    expect(toPrune).toContain('skill-37');
    expect(toPrune).not.toContain('skill-36');
    expect(toPrune).not.toContain('skill-1');
  });

  test('手動建立的 skill（不在 lifecycle.jsonl）不被歸檔', () => {
    for (let i = 1; i <= 37; i++) createSkill(`skill-${i}`);
    appendLifecycleEntry({ action: 'forge', skillName: 'skill-36', date: '2026-03-17' });

    const allSkills = listSkills();
    const referenced = collectReferenced();
    const autoGenerated = collectAutoGenerated();
    const toPrune = allSkills.filter((s) => !referenced.has(s) && autoGenerated.has(s));

    expect(toPrune).toEqual(['skill-36']);
    expect(toPrune).not.toContain('skill-1');
    expect(toPrune).not.toContain('skill-37');
  });
});

// ─── checkSkillHealth 邏輯 ─────────────────────────────────────────────────────

describe('checkSkillHealth 邏輯', () => {
  test('正確計算 total / referenced / unreferenced', () => {
    createSkill('alpha');
    createSkill('beta');
    createSkill('gamma');
    createAgent('executor', ['alpha', 'beta']);

    const allSkills = listSkills();
    const referencedSet = collectReferenced();
    const result = {
      total: allSkills.length,
      referenced: allSkills.filter((s) => referencedSet.has(s)),
      unreferenced: allSkills.filter((s) => !referencedSet.has(s)),
    };

    expect(result.total).toBe(3);
    expect(result.referenced).toContain('alpha');
    expect(result.referenced).toContain('beta');
    expect(result.unreferenced).toContain('gamma');
    expect(result.unreferenced).not.toContain('alpha');
  });

  test('無 skills 時 total 為 0', () => {
    const allSkills = listSkills();
    const referencedSet = collectReferenced();
    const result = {
      total: allSkills.length,
      referenced: allSkills.filter((s) => referencedSet.has(s)),
      unreferenced: allSkills.filter((s) => !referencedSet.has(s)),
    };
    expect(result.total).toBe(0);
    expect(result.referenced).toEqual([]);
    expect(result.unreferenced).toEqual([]);
  });

  test('全部 skill 未被引用時 unreferenced = all', () => {
    createSkill('orphan-1');
    createSkill('orphan-2');

    const allSkills = listSkills();
    const referencedSet = collectReferenced();
    const unreferenced = allSkills.filter((s) => !referencedSet.has(s));

    expect(unreferenced.length).toBe(2);
    expect(unreferenced).toContain('orphan-1');
    expect(unreferenced).toContain('orphan-2');
  });
});
